FROM node:20-alpine

# Install bash
RUN apk add --no-cache bash

# Gemini CLI
RUN npm install -g @google/gemini-cli

# Claude Code
RUN npm install -g @anthropic-ai/claude-code

WORKDIR /app
COPY ./package*.json ./

RUN npm install
COPY . .
EXPOSE 3000

CMD ["npm", "run", "dev"]