services:
  dev-web:
    container_name: personal-web-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/app
      - /app/node_modules
      - ./gemini:/root/.gemini
    ports:
      - "3030:3000"
    extra_hosts:
      - "host.docker.internal:127.0.0.1"
    environment:
      - WATCHPACK_POLLING=true
      - GOOGLE_CLOUD_PROJECT=erudite-nation-470903-t5
    tty: true
    stdin_open: true