FROM node:20-alpine

RUN apk add --no-cache vips-dev build-base bash
RUN npm install -g npm@latest

WORKDIR /app
COPY ./package*.json ./

RUN npm install --include=optional
COPY . .

EXPOSE 1337
CMD ["npm", "run", "develop"]